ecommerce/cart/urls.py
from django.urls import path
from cart import views

app_name="cart"

urlpatterns = [
    path('addtocart/<int:i>',views.add_to_cart,name="addtocart"),
    path('cartview',views.cart_view,name="cartview"),
    path('cartremove/<int:i>',views.cart_remove,name="cartremove"),
    path('cartdelete/<int:i>',views.cart_delete,name="cartdelete"),
    path('orderform',views.order_form,name="orderform"),
    path('status/<u>',views.payment_status,name="status"),
    path('orderview',views.order_view,name="orderview"),

]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search.urls')),
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.urls import path
from search import views

app_name='search'

urlpatterns = [
    path('',views.search_product,name="search"),

]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views

app_name="shop"

urlpatterns = [
    path('',views.allcategories,name="category"),
    path('products/<int:p>',views.allproducts,name="products"),
    path('productdetail/<int:p>',views.productdetails,name="detail"),
    path('register/', views.register, name="register"),
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('addcat',views.addcategory,name="addcat"),
    path('addpro',views.addproduct,name="addpro"),
    path('addstock/<int:p>',views.add_stock,name="addstock"),

]

ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User

class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    date_added=models.DateTimeField(auto_now_add=True)

    def subtotal(self):
        return self.product.price*self.quantity


class order_details(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    address=models.TextField()
    phone_no=models.BigIntegerField()
    pin=models.IntegerField()

    order_id=models.CharField(max_length=100,blank=True)
    ordered_date=models.DateTimeField(auto_now_add=True)

    payment_status=models.CharField(max_length=20,default="pending")
    delivery_status=models.CharField(max_length=20,default="pending")

class Payment(models.Model):
    name=models.CharField(max_length=100)
    amount=models.IntegerField()
    order_id=models.CharField(max_length=50,blank=True)
    razorpay_payment_id=models.CharField(max_length=50,blank=True)
    paid=models.BooleanField(default=False)

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/cart/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import login
from cart.models import Cart,Payment,order_details
from django.views.decorators.csrf import csrf_exempt
from shop.models import Product
import razorpay

@login_required
def add_to_cart(request,i):
    p=Product.objects.get(id=i)
    u=request.user
    try:
        c = Cart.objects.get(user=u,product=p)
        if(p.stock>0):
            c.quantity+=1
            c.save()
            p.stock-=1
            p.save()

    except:
        c=Cart.objects.create(product=p,user=u,quantity=1)
        c.save()
        p.stock-=1
        p.save()

    return redirect('cart:cartview')

@login_required
def cart_view(request):
    u=request.user
    total=0
    c=Cart.objects.filter(user=u)
    for i in c:
        total+=i.quantity*i.product.price
    return render(request,'cart.html',{'cart':c,'total':total})


def cart_remove(request,i):
    p=Product.objects.get(id=i)
    u=request.user

    try:
        c=Cart.objects.get(user=u,product=p)
        if(c.quantity>1):
            c.quantity-=1
            c.save()
            p.stock+=1
            p.save()
        else:
            c.delete()
            p.stock += 1
            p.save()
    except:
        pass
    return redirect('cart:cartview')

def cart_delete(request,i):
    p=Product.objects.get(id=i)
    u=request.user

    try:
        c=Cart.objects.get(user=u,product=p)
        c.delete()
        p.stock += c.quantity
        p.save()
    except:
        pass
    return redirect('cart:cartview')

def order_form(request):
    if(request.method=="POST"):
        address=request.POST['a']
        phone=request.POST['p']
        pin=request.POST['pi']

        u=request.user
        c=Cart.objects.filter(user=u)

        total=0
        for i in c:
            total+=i.quantity*i.product.price
        total=int(total*100)
        client=razorpay.Client(auth=('rzp_test_cQky6LUBsfvART','UOkwN4DKb9k2dZF8kDqedkA2')) #creates a client connection
        # using razorpay id and secret code

        response_payment=client.order.create(dict(amount=total,currency="INR"))  #creates an order with razorpay using razorpay client
        # print(response_payment)
        order_id=response_payment['id']  #Retrieves the order_id from response
        order_status=response_payment['status'] #retrive status from response
        if(order_status == "created"):  #if status is created then store order_id in payment and order_detail table
            p=Payment.objects.create(name=u.username,amount=total,order_id=order_id)
            p.save()
            for i in c:
                o=order_details.objects.create(product=i.product,user=u,no_of_items=i.quantity,address=address,phone_no=phone,pin=pin,order_id=order_id)
                o.save()
        else:
            pass

        response_payment['name']=u.username #additional information name

        return render(request,'payment.html',{'payment':response_payment})



    return render(request,'orderform.html')


@csrf_exempt
def payment_status(request,u):
    user = User.objects.get(username=u)
    if (not request.user.is_authenticated):  # if user is not authenticated
        login(request, user)  # allowing request user to login
    if (request.method == "POST"):
        response = request.POST
        print(response)
        print(u)

        param_dict = {
            'razorpay_order_id': response['razorpay_order_id'],
            'razorpay_payment_id': response['razorpay_payment_id'],
            'razorpay_signature': response['razorpay_signature'],
        }

        client = razorpay.Client(auth=('rzp_test_cQky6LUBsfvART', 'UOkwN4DKb9k2dZF8kDqedkA2'))
        print(client)

        try:
            status=client.utility.verify_payment_signature(param_dict) #to check the authenticity of the razorpay signature
            print(status)
            # to retrieve a particular record in payment table whole order id matches the response order is
            p = Payment.objects.get(order_id=response['razorpay_order_id'])
            p.razorpay_payment_id = response['razorpay_payment_id']  # adds the payment id after successfull payment
            p.paid = True  # changes paid status to true
            p.save()

            # user = User.objects.get(username=u)
            o = order_details.objects.filter(user=user, order_id=response['razorpay_order_id'])  # retrieve the particular record in order_details
            # matching with current user and response order_id
            for i in o:
                i.payment_status = "paid"
                i.save()

            # after successful payment deletes the item in cart for particular user
            c = Cart.objects.filter(user=user)
            c.delete()



        except:
            print("hello")



    return render(request, 'payment_status.html',{'status':status})

def order_view(request):
    u=request.user
    o=order_details.objects.filter(user=u)

    return render(request,'order_view.html',{'orders':o})

ecommerce/search/views.py
from django.shortcuts import render

from django.shortcuts import render
from shop.models import Product
from django.db.models import Q

def search_product(request):
    query=""
    p=None
    if request.method=="POST":
        query=request.POST['q']
        if query:
            p=Product.objects.filter(Q(name__icontains=query) | Q(desc__icontains=query))

    return render(request,'search.html',{'product':p,'q':query})

ecommerce/templates/addstock.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<h2 class="text-center" style="margin-top:200px;">ADD STOCK</h2>
<div class="container" style="width:40%;margin-bottom:100px;">

<form method="POST">
  {% csrf_token %}


  <div class="mb-3">

    <input type="number" class="form-control" name="n" value="{{product.stock}}" placeholder="Enter stock">
  </div>

  <div>
  <button type="submit" class="button">submit</button>
  </div>


</form>

</div>


{% endblock %}

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
<title>Covet</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="Wish shop project">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Stylesheets -->
<link rel="stylesheet" type="text/css" href="{% static 'styles/bootstrap4/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/animate.css' %}">
<link rel="stylesheet" href="{% static 'plugins/colorbox/colorbox.css' %}" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'styles/main_styles.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/responsive.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/cart.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/cart_responsive.css' %}">
	<link rel="stylesheet" href="{% static 'styles/button.css' %}">


</head>
<body>

<div class="super_container">

	<!-- Header -->

	<header class="header" style="margin-bottom:100px;">
		<div class="header_inner d-flex flex-row align-items-center justify-content-start">
			<div class="logo"><a href="#">Covet</a></div>
			<nav class="main_nav">
				<ul>
					<li><a href="{% url 'shop:category' %}">home</a></li>
					{% for i in links %}
            			<li><a href="{% url 'shop:products' i.id %}">{{i.name}}</a></li>
              		{% endfor %}
				</ul>
			</nav>
			<div class="search header_search">
					<form class="d-flex" method="POST" action="{% url 'search:search' %}">
          				{% csrf_token %}
        				<input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        				<button class="btn " type="submit">Search</button>
      				</form>
				</div>
			<div class="header_content ml-auto">
				<div class="shopping">
					<!-- Cart -->
					{% if user.is_authenticated %}
					{% if user.is_superuser == False %}
					<a href="{% url 'cart:cartview' %}">
						<div class="cart">
							<img src="{% static 'images/shopping-bag.svg' %}" alt="">
							<div class="cart_num_container">
								<div class="cart_num_inner">
									<div class="cart_num">{{c}}</div>
								</div>
							</div>
						</div>
					</a>
					{% endif %}
					{% endif %}
					<!-- Star -->
<!--					<a href="#">-->
<!--						<div class="star">-->
<!--							<img src="{% static 'images/star.svg' %}" alt="">-->
<!--							<div class="star_num_container">-->
<!--								<div class="star_num_inner">-->
<!--									<div class="star_num">0</div>-->
<!--								</div>-->
<!--							</div>-->
<!--						</div>-->
<!--					</a>-->
					<!-- Avatar -->
<!--					<a href="#">-->
<!--						<div class="avatar">-->
<!--							<img src="{% static 'images/avatar.svg' %}" alt="">-->
<!--						</div>-->
<!--					</a>-->
				</div>
			</div>

			<div class="burger_container d-flex flex-column align-items-center justify-content-around menu_mm"><div></div><div></div><div></div></div>
		</div>
	</header>

	<!-- Menu -->

	<div class="menu d-flex flex-column align-items-end justify-content-start text-right menu_mm trans_400">
		<div class="menu_close_container"><div class="menu_close"><div></div><div></div></div></div>
		<div class="logo menu_mm"><a href="#"></a></div>
		<div class="search">
			<form method="POST" action="{% url 'search:search' %}">
				{% csrf_token %}
				<input type="search" class="search_input menu_mm" required="required" name="q">
				<button type="submit" id="search_button_menu" class="search_button menu_mm"><img class="menu_mm" src="{% static 'images/magnifying-glass.svg' %}" alt=""></button>
			</form>
		</div>
		<nav class="menu_nav">
			<ul class="menu_mm">
				<li class="menu_mm"><a href="{% url 'shop:category' %}">home</a></li>
				{% for i in links %}
            			<li><a href="{% url 'shop:products' i.id %}">{{i.name}}</a></li>
				{% endfor %}

				{% if user.is_authenticated %}
				{% if user.is_superuser == False %}
				<li class="menu_mm"><a href="{% url 'cart:orderview' %}">Your orders</a></li>
				{% else %}
					<li class="menu_mm"><a href="{% url 'shop:addcat' %}">Add category</a></li>
					<li class="menu_mm"><a href="{% url 'shop:addpro' %}">Add product</a></li>
				{% endif %}

				<li class="menu_mm"><a href="{% url 'shop:logout' %}">Logout</a></li>
				{% else %}
				<li class="menu_mm"><a href="{% url 'shop:register' %}">Register</a></li>
				<li class="menu_mm"><a href="{% url 'shop:login' %}">Login</a></li>

				{% endif %}

			</ul>
		</nav>
	</div>

    {% block content %}
    {% endblock %}


	<!-- Footer -->

	<footer class="footer">
		<div class="container-fluid">
			<div class="row">
				<div class="col text-center">
					<div class="footer_logo"><a href="#">Covet</a></div>
					<nav class="footer_nav">
						<ul>
							<li><a href="{% url 'shop:category' %}">home</a></li>
							{% for i in links %}
            					<li><a href="{% url 'shop:products' i.id %}">{{i.name}}</a></li>
              				{% endfor %}
						</ul>
					</nav>
					<div class="footer_social">
						<ul>
							<li><a href="https://www.pinterest.com/sarahandaric/references-for-art/"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
							<li><a href="https://www.linkedin.com/in/sada-yoosuf-b60591258/"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
							<li><a href="https://www.instagram.com/sada._.yoosuf/"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
							<li><a href="https://www.reddit.com"><i class="fa fa-reddit-alien" aria-hidden="true"></i></a></li>
							<li><a href="https://x.com/?lang=en"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
						</ul>
					</div>
					<div class="copyright"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></div>
				</div>
			</div>
		</div>
	</footer>
</div>

<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'styles/bootstrap4/popper.js' %}"></script>
<script src="{% static 'styles/bootstrap4/bootstrap.min.js' %}"></script>
<script src="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.js' %}"></script>
<script src="{% static 'plugins/easing/easing.js' %}"></script>
<script src="{% static 'plugins/parallax-js-master/parallax.min.js' %}"></script>
<script src="{% static 'plugins/colorbox/jquery.colorbox-min.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>
<script src="{% static 'js/cart_custom.js' %}"></script>
</body>
</html>

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}



<div class="row" style="margin-bottom:50px;">
    <div class="col-12" style="position: relative;">
        <!-- Image with Shopping Cart text overlay -->
        <img src="{% static 'images/cart.jpg' %}" height="400px" width="100%" alt="Shopping Cart">

        <!-- Text overlay container -->
		<div class="home_content text-center" style="color: white;left:15%;">
    		<h3 class="home_title" style="font-size: 2rem;">Shopping Cart</h3>
			<div class="breadcrumbs">
				<ul>
					<li><a href="{% url 'shop:category' %}" style="color: white;">Home</a></li>
					<li style="color: white;">Shopping Cart</li>
				</ul>
			</div>
		</div>
    </div>
</div>


<!--cart table-->
<div class="cart_container">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="cart_title">your shopping cart</div>
				</div>
			</div>
			<div class="row">
				<div class="col">
					<div class="cart_bar d-flex flex-row align-items-center justify-content-start">
						<div class="cart_bar_title_name">Product</div>
						<div class="cart_bar_title_content ml-auto">
							<div class="cart_bar_title_content_inner d-flex flex-row align-items-center justify-content-end">
								<div class="cart_bar_title_price">Price</div>
								<div class="cart_bar_title_quantity">Quantity</div>
								<div class="cart_bar_title_total">Total</div>
								<div class="cart_bar_title_button"></div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col">
					<div class="cart_products">
						<ul>
							{% for i in cart %}
							<li class=" cart_product d-flex flex-md-row flex-column align-items-md-center align-items-start justify-content-start">
								<!-- Product Image -->
								<div class="cart_product_image"><img src="{{i.product.image.url}}" height="100px" width="100px"></div>
								<!-- Product Name -->
								<div class="cart_product_name"><a href="product.html">{{i.product.name}}</a></div>
								<div class="cart_product_info ml-auto">
									<div class="cart_product_info_inner d-flex flex-row align-items-center justify-content-md-end justify-content-start">
										<!-- Product Price -->
										<div class="cart_product_price">{{i.product.price}}</div>
										<!-- Product Quantity -->
										<div class="product_quantity_container">
											<div class="product_quantity clearfix">
    										<input type="text" value="{{i.quantity}}" readonly>
    										<div class="quantity_buttons">
												{% if i.product.stock > 0 %}
												<!-- Increment quantity button -->
												<div>
        											<a href="{% url 'cart:addtocart' i.product.id %}">
            										<i class="fa fa-caret-up" aria-hidden="true" style="color:black;"></i>
        											</a>
												</div>
        										<!-- Decrement quantity button -->
												<div>
													<a href="{% url 'cart:cartremove' i.product.id %}">
            										<i class="fa fa-caret-down" aria-hidden="true" style="color:black;"></i>
													</a>
												</div>
												{% else %}
												<div>
													<a href="{% url 'cart:cartremove' i.product.id %}">
            										<i class="fa fa-caret-down" aria-hidden="true" style="color:black;"></i>
													</a>
												</div>
												{% endif %}

    										</div>
											</div>

										</div>
										<!-- Products Total Price -->
										<div class="cart_product_total" id="total_{{i.product.id}}">{{i.subtotal}}</div>
										<!-- Product Cart Trash Button -->
										<div class="cart_product_button">
    										<a href="{% url 'cart:cartdelete' i.product.id %}">
        										<img src="{% static 'images/trash.png' %}">
    										</a>
										</div>
									</div>
								</div>
							</li>
							{% endfor %}
						</ul>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col">
					<div class="cart_control_bar d-flex flex-md-row flex-column align-items-start justify-content-start">
<!--						<button class="button_clear cart_button">clear cart</button>-->
<!--						<button class="button_update cart_button">update cart</button>-->
<!--						<button class="button_update cart_button_2 ml-md-auto">continue shopping</button>-->
						<a href="{% url 'shop:category' %}" class="button_update cart_button_2 ml-md-auto text-center" style="display: inline-block; padding: 10px 20px; text-align: center; width: 25%;">
        					continue shopping
    					</a>
					</div>
				</div>
			</div>
			<div class="row cart_extra">
				<!-- Cart Coupon -->
<!--				<div class="col-lg-6">-->
<!--					<div class="cart_coupon">-->
<!--						<div class="cart_title">coupon code</div>-->
<!--						<form action="#" class="cart_coupon_form d-flex flex-row align-items-start justify-content-start" id="cart_coupon_form">-->
<!--							<input type="text" class="cart_coupon_input" placeholder="Coupon code" required="required">-->
<!--							<button class="button_clear cart_button_2">apply coupon</button>-->
<!--						</form>-->
<!--					</div>-->
<!--				</div>-->
				<!-- Cart Total -->
				<div class="col-lg-5 offset-lg-1">
					<div class="cart_total">
						<div class="cart_title">cart total</div>
						<ul>
<!--							<li class="d-flex flex-row align-items-center justify-content-start">-->
<!--								<div class="cart_total_title">Subtotal</div>-->
<!--								<div class="cart_total_price ml-auto">$35.00</div>-->
<!--							</li>-->
<!--							<li class="d-flex flex-row align-items-center justify-content-start">-->
<!--								<div class="cart_total_title">Shipping</div>-->
<!--								<div class="cart_total_price ml-auto">$5.00</div>-->
<!--							</li>-->
							<li class="d-flex flex-row align-items-center justify-content-start">
								<div class="cart_total_title">Total</div>
								<div class="cart_total_price ml-auto">{{total}}</div>
							</li>
						</ul>
						<a href="{% url 'cart:orderform' %}" class="button_update cart_button_2 ml-md-auto text-center mt-1" style="display: inline-block; padding: 10px 20px; text-align: center; width: 100%;">
        					proceed to checkout
    					</a>
					</div>
				</div>
			</div>
		</div>
	</div>




{% endblock %}

ecommerce/templates/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="product" style="margin-bottom:100px;margin-top:200px;">
		<div class="container">
			<div class="row product_row">

				<!-- Product Image -->
				<div class="col-lg-7">
					<div class="product_image">
						<div class="product_image_large"><img src="{{product.image.url}}" height="400px" width="80%" alt=""></div>
						<div class="product_image_thumbnails d-flex flex-row align-items-start justify-content-start">
<!--							<div class="product_image_thumbnail" style="background-image:url(images/product_image_1.jpg)" data-image="images/product_image_1.jpg"></div>-->
<!--							<div class="product_image_thumbnail" style="background-image:url(images/product_image_2.jpg)" data-image="images/product_image_2.jpg"></div>-->
<!--							<div class="product_image_thumbnail" style="background-image:url(images/product_image_4.jpg)" data-image="images/product_image_4.jpg"></div>-->
						</div>
					</div>
				</div>

				<!-- Product Content -->
				<div class="col-lg-5">
					<div class="product_content">
						<h2 class="product_name">{{product.name}}</h2>
                        <p>{{product.desc}}</p>
						<div class="product_price">Rs: {{product.price}}</div>
						<div class="rating rating_4" data-rating="4">
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
						</div>
						<!-- In Stock -->
						<div class="in_stock_container">
							<div class="in_stock in_stock_true"></div>
							<span>stock:{{product.stock}}</span>
                            <p class="card-text">available:{{product.available}}</p>
						</div>

						<div class="product_size_container">
							{% if user.is_superuser == True %}
          						{% if product.stock > 0 %}
            						<h5>Product In stock</h5>
            						<div class="button mt-5"><a href="{% url 'shop:addstock' product.id %}">add stock</a></div>
          						{% else %}
            						<h5>Product Out of Stock</h5>
            						<div class="button mt-5"><a href="{% url 'shop:addstock' product.id %}">add stock</a></div>
          						{% endif %}
        					{% else %}
          						{% if product.stock > 0 %}
            						<h5>Product In Stock</h5>
            						<div class="button mt-5"><a href="{% url 'cart:addtocart' product.id %}">add to cart</a></div>
          						{% else %}
            						<h5>Out of Stock</h5>
          						{% endif %}
        					{% endif %}


  						</div>


						</div>
					</div>
				</div>
			</div>
		</div>


{% endblock %}

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!--category banner image-->
<div class="row" style="margin-top:100px;">
    <div class="col-12">
        <img src="{{cat.image.url}}" height="400px" width="100%">
    </div>

</div>

<!--category title and description-->
<div class="row mt-3" style="margin-bottom:100px;">
    <div class="col-12">
        <h2 class="text-center fw-bold mt-2 mb-2">{{cat.name}}</h2>

    </div>

</div>

<!--product cards display-->
<div class="container mt-5" style="margin-bottom:100px;">
<div class="row">
	{% for i in product %}

				<div class="col-sm-4">

					<!-- Products -->

					<div class="product_grid">

						<!-- Product -->
						<div class="product">
<!--							on clicking image moves to detail page-->
							<a href="{% url 'shop:detail' i.id %}">
							<div class="product_image"><img src="{{i.image.url}}" alt="" height="400px" width="100%"></div>
							</a>
							<div class="rating rating_4" data-rating="4">
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
							</div>
							<div class="product_content clearfix">
								<div class="product_info">
									<div class="product_name"><a href="{% url 'shop:detail' i.id %}">{{i.name}}</a></div>
									<div class="product_price">Rs: {{i.price}}</div>
								</div>
								<div class="product_options">
									<div class="product_buy product_option"><a href="{% url 'cart:addtocart' i.id %}"><img src="{% static 'images/shopping-bag-white.svg' %}" alt=""></a></div>
									<div class="product_fav product_option"><a href="{% url 'cart:addtocart' i.id %}" style="color: black;" target="_blank">+</a></div>
								</div>
							</div>
						</div>

					</div>
				</div>
	{% endfor %}

			</div>
	</div>




{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}



{% block content %}

<div class="container mt-5" style="margin-bottom:100px;">
	<h3 class="text-center" style="margin-top:200px;">you have searched for <span>{{q}}</span></h3>
</div>

<div class="container mt-5" style="margin-bottom:100px;">
    {% if product == None %}
    <h3 class="text-center">No Results Found </h3>
<!--    if no query entered by user -->
    {% else %}
<div class="row">
	{% for i in product %}

				<div class="col-sm-4">

					<!-- Products -->

					<div class="product_grid">

						<!-- Product -->
						<div class="product">
<!--							on clicking image moves to detail page-->
							<a href="{% url 'shop:detail' i.id %}">
							<div class="product_image"><img src="{{i.image.url}}" alt="" height="400px" width="100%"></div>
							</a>
							<div class="rating rating_4" data-rating="4">
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
							</div>
							<div class="product_content clearfix">
								<div class="product_info">
									<div class="product_name"><a href="{% url 'shop:detail' i.id %}">{{i.name}}</a></div>
									<div class="product_price">${{i.price}}</div>
								</div>
								<div class="product_options">
									<div class="product_buy product_option"><img src="{% static 'images/shopping-bag-white.svg' %}" alt=""></div>
									<div class="product_fav product_option">+</div>
								</div>
							</div>
						</div>

					</div>
				</div>
 			{% empty %}
<!--        if product sequence empty -->
			<h3 class="text-center">No Results found</h3>
	{% endfor %}

</div>
{% endif %}
</div>

{% endblock %}